### ISSUE TITLE
no signal on pins

### ISSUE THREAD

**Issue by khoroshyy** [n8vi/pru-dds#9]
Hi, I have managed to run the pru-dds, and it runs without complains. But if I run it with frequency set to 10kHz and connect oscilloscope to any of the outputs, I see no signal at all. I was expecting some high/low jumps. Any idea where I can look to find out what is wrong?
Thanks

**Comment by n8vi** [comment]
Hi, I've been away from this project for a while and will be updating it to run on newer beaglebones soon.  Are you still having this issue?

**Comment by n8vi** [comment]
There are some clues as to how to fix this in the readme.  Open a new issue if this is still occurring, thanks.
